Add configuration option for what noise function to use, to allow worlds created in 2.2.0.0 to continue using opensimplex
GTNewHorizons/Realistic-World-Gen pull request #4
Opened 2022-10-05 22:24 UTC by dvdmandt

GTNH 2.2.0.0 unintentionally introduced a change to world gen caused by using our own build of RWG, which turned out to have 7 years old changes in its source code that were not in the CurseForge binary we had been using until now. This change has been reverted to avoid ugly chunk borders in worlds upgrading from a previous GTNH version, but said revert will instead cause those chunk borders whenever a world created in 2.2.0.0 is updated to the next version. This PR introduces a way to switch between the two through a config option or ingame command (/rwg_noise <default|opensimplex|perlin>).

2022-10-05 22:46 UTC, Ydrec commented
This noise generator may need further tweaking, as observed in 2200 it caused massive biome borders being generated, generation became extremely mountainous without respect to biome type and almost no villages being generated.

2022-10-05 22:54 UTC, dvdmandt commented
I don't disagree with you, but that may be a different issue and PR. The whole idea of this is to allow existing worlds created in any function to continue to work without chunk borders. The "old" worldgen we've now reverted to is fine and should be used for any new worlds imho.

2022-10-06 06:30 UTC, eigenraven reviewed
Looks good overall, I'd just remove "default" as a config option and just set the default value to "perlin"

2022-10-06 23:44 UTC, dvdmandt commented
I've now moved away from the config option and instead shifted to using the /rwg_noise command to set noise function for the current world. It needs more testing with worlds from 2.2.0.0 and other versions, and it needs some cleanup. Possibly also some permission checks on said command.

2022-10-06 23:46 UTC, dvdmandt commented
It also needs to set the noise type on world creation.

2022-12-16 17:44 UTC, dvdmandt commented
I've now removed the warning message on login as we can't detect new worlds. We'll just have to inform users in another way. At least now there's a command to enable compatibility on a per world basis:

`/rwg_noise perlin` for the intended worldgen
`/rwg_noise opensimplex` for the 2.2.0.0 version

2022-12-16 17:48 UTC, dvdmandt commented
I'm marking this as no longer a draft as this is better than nothing and I have no idea when I'll be able to complete it to the level I want. The check that failed was downloading the MC client to build I think.

2022-12-20 06:41 UTC, Dream-Master commented
@dvdmandt so this is ready for a review ?

2022-12-21 10:32 UTC, Dream-Master commented
DvDmanDT — Today at 10:45 AM
It's ready. It was fixed before, but in a way that "breakes" worlds created in that version. This allows users who created worlds in 2.2.0.0 to continue using the "wrong" generator.

2022-12-21 10:32 UTC, Dream-Master commented
@eigenraven maybe you can have a look later? thanks

2022-12-21 10:38 UTC, eigenraven requested changes

2022-12-21 10:38 UTC, eigenraven commented on src/main/java/rwg/commands/RwgBugInfoCommand.java
> +        "A bug in the RWG version shipped with GTNH 2.2.0.0 caused the world to be generated differently than previous versions.",
All of these need to be translation strings

2022-12-21 10:38 UTC, eigenraven commented on src/main/java/rwg/commands/RwgNoiseCommand.java
> +            sender.addChatMessage(new ChatComponentText("Current noise type is " + current));
Same here, replace ChatComponentText with the localizable variant and put the messages into the language file.

2022-12-21 10:38 UTC, eigenraven commented on src/main/java/rwg/handlers/LoginHandler.java
> +        //        if (RwgWorldSavedData.getNoiseImplementation() == NoiseImplementation.UNKNOWN) {
Commented code?

2022-12-22 08:10 UTC, eigenraven submitted a review, later dismissed

2022-12-22 08:52 UTC, boubou19 approved these changes

2022-12-22 08:52 UTC, merged